name: logisticsroutes-osrm

services:
  osrm:
    image: ghcr.io/project-osrm/osrm-backend@sha256:8a1b1bc938412f15f9b5b32d794c4ec6bf4a85dfbbabfa0a014b70b187edb53b
    command: ["osrm-routed", "--algorithm", "mld", "/data/moldova-latest.osrm"]
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./data/osrm:/data:ro
    restart: unless-stopped
