<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>5ac41e00-b9ba-4b9b-bf5a-aa8c1e11ceba</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.24" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.31">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Npgsql" Version="8.0.9" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\LogisticsRoutes.BusinessLayer\LogisticsRoutes.BusinessLayer.csproj" />
    </ItemGroup>

</Project>
